/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Found %s devices. Added %s new devices.": {     "en": "Found %s devices. Added %s new devices.",         "de": "%s Geräte gefunden. %s neue Geräte hinzugefügt.", "ru": "Найдено %s устройств. Добавлено %s новых устройств.", "pt": "Encontrados %s dispositivos. Adicionado %s novos dispositivos.", "nl": "%s apparaten gevonden. %s nieuwe apparaten toegevoegd.", "fr": "Trouvé %s appareils. Ajout de %s nouveaux périphériques.", "it": "Trovato dispositivi di %s. Aggiunti %s nuovi dispositivi.", "es": "Encontrado %s dispositivos. Se agregaron %s nuevos dispositivos.", "pl": "Znaleziono urządzenia %s. Dodano %s nowych urządzeń.", "zh-cn": "找到％s个设备。"},
    "Found %s devices. Nothing new.": {              "en": "Found %s devices. No new device were added.",     "de": "%s Geräte gefunden. Es wurden keine neuen Geräte hinzugefügt.", "ru": "Найдено %s устройств. Ничего нового.",            "pt": "Encontrados %s dispositivos. Nada de novo.",      "nl": "%s apparaten gevonden. Niets nieuws.",            "fr": "Trouvé %s appareils. Rien de nouveau.",           "it": "Trovato dispositivi di %s. Niente di nuovo.",     "es": "Encontrado %s dispositivos. Nada nuevo.",         "pl": "Znaleziono urządzenia %s. Nic nowego.",           "zh-cn": "找到％s个设备。"},
    "IP": {                                          "en": "IP",                                              "de": "IP-Adresse",                                      "ru": "IP",                                              "pt": "IP",                                              "nl": "IP",                                              "fr": "IP",                                              "it": "IP",                                              "es": "IP",                                              "pl": "IP",                                              "zh-cn": "知识产权"},
    "Name": {                                        "en": "Name",                                            "de": "Name",                                            "ru": "Имя",                                             "pt": "Nome",                                            "nl": "Naam",                                            "fr": "prénom",                                          "it": "Nome",                                            "es": "Nombre",                                          "pl": "Imię",                                            "zh-cn": "名称"},
    "No devices found": {                            "en": "No devices found",                                "de": "Keine Geräte gefunden",                           "ru": "Не найдено ни одного устройства",                 "pt": "Nenhum dispositivo encontrado",                   "nl": "Geen apparaten gevonden",                         "fr": "Aucun périphérique trouvé",                       "it": "Nessun dispositivo trovato",                      "es": "No se encontraron dispositivos",                  "pl": "Nie znaleziono urządzeń",                         "zh-cn": "找不到设备"},
    "Password": {                                    "en": "Password",                                        "de": "Passwort",                                        "ru": "Пароль",                                          "pt": "Senha",                                           "nl": "Wachtwoord",                                      "fr": "Mot de passe",                                    "it": "Parola d'ordine",                                 "es": "Contraseña",                                      "pl": "Hasło",                                           "zh-cn": "密码"},
    "Scan devices": {                                "en": "Scan for devices",                                "de": "Nach Geräten suchen",                             "ru": "Сканировать устройства",                          "pt": "Dispositivos de digitalização",                   "nl": "Apparaten scannen",                               "fr": "Appareils de numérisation",                       "it": "Scansione dei dispositivi",                       "es": "Escanear dispositivos",                           "pl": "Skanuj urządzenia",                               "zh-cn": "扫描装置"},
    "The scan can last over one minute or even longer. Be patient...": {"en": "The scan can last over one minute or even longer. Please be patient …", "de": "Die Suche kann länger als eine Minute dauern. Bitte geduldig sein …", "ru": "Сканирование может длиться более одной минуты или даже дольше. Потерпи...", "pt": "A varredura pode durar mais de um minuto ou até mais. Seja paciente...", "nl": "De scan kan meer dan een minuut of zelfs langer duren. Wees geduldig...", "fr": "L'analyse peut durer plus d'une minute ou même plus longtemps. Sois patient...", "it": "La scansione può durare più di un minuto o anche più. Essere pazientare...", "es": "El escaneo puede durar más de un minuto o incluso más. Se paciente...", "pl": "Skanowanie może trwać ponad minutę lub nawet dłużej. Bądź cierpliwy...", "zh-cn": "扫描可能持续一分钟甚至更长的时间。"},
    "The scan will take approx 5s ...": {            "en": "The scan will take approx. 5 seconds …",          "de": "Der Scan dauert ungefähr 5 Sekunden …",           "ru": "Сканирование займет около 5 с ...",               "pt": "A digitalização demora cerca de 5s ...",          "nl": "De scan duurt ongeveer 5s ...",                   "fr": "Le scan prendra environ 5 secondes ...",          "it": "La scansione richiederà circa 5 secondi ...",     "es": "El escaneo tomará aproximadamente 5s ...",        "pl": "Skanowanie zajmie około 5 sekund ...",            "zh-cn": "扫描大约需要5秒......"},
    "Username": {                                    "en": "Username",                                        "de": "Benutzername",                                    "ru": "Имя пользователя",                                "pt": "Nome de usuário",                                 "nl": "Gebruikersnaam",                                  "fr": "Nom d'utilisateur",                               "it": "Nome utente",                                     "es": "Nombre de usuario",                               "pl": "Nazwa Użytkownika",                               "zh-cn": "用户名"},
};